### ISSUE TITLE
Как скачать приложение?

### ISSUE THREAD

**Issue by Vivarko** [Titlehhhh/Minecraft-Bot-Manager#2]

**Comment by Titlehhhh** [comment]
Ничего себе так то меня кто то увидел...
 Ну ладно, я пока замедлил разработку, так как к ЕГЭ готовлюсь.
Да и приложение не особо обладает функциями, только пока подключение, даже нет чата(есть но не работает). Наверное нужно вам подождать.

**Comment by Vivarko** [comment]
Как-то долго уже не идёт работа над приложением

**Comment by Titlehhhh** [comment]
Я буду честным. Я забил на разработку. Нету задачи.

Раньше играл в Майнкрафт были задачи, например сделать быстрого бота для афк рыбалки, но теперь не интересно.

Плюс к этому winui3, на котором я собирался делать обновленную версию программы, весь в багах.

А вам зачем нужна эта программа?

**Comment by Titlehhhh** [comment]
Я забил на неё... Реально. Нет мотивации и задачи. Я вообще делал программу
для себя, чтобы автоматизировать и оптимизировать АФК рыбалки и т.д.
Потом перестал играть в майн так и стало не интересно.

А у вас какая цель использования приложения?

вт, 21 июн. 2022 г., 13:30 Chill Room Team ***@***.***>:
